variables:
  DOCKER_DRIVER: overlay2
  IMAGE_VERSION: latest

stages:
  - build
  - deploy
  - production

BUILD_DEV:
  stage: build
  when: always
  image: docker:18.09.7
  services:
  - docker:18.09.7-dind

  script:
    - echo $CI_REGISTRY_IMAGE:$IMAGE_VERSION
    - docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_VERSION .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_VERSION

DEPLOY_DEV:
  stage: deploy
  needs:
    - BUILD_DEV
  image: alpine

  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$DEV_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$ENV_DEV" > dev.env
    
  script:
    - scp -o StrictHostKeyChecking=no dev.env deployer@18.141.31.96:~/$CI_PROJECT_NAME/dev.env
    - ssh -o StrictHostKeyChecking=no deployer@18.141.31.96 "cd $CI_PROJECT_NAME; docker-compose pull; docker-compose up -d"

DEPLOY_PRODUCTION:
  stage: production
  when: manual
  needs:
    - DEPLOY_DEV
  image: alpine

  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$PROD_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

  script:
    - ssh -o StrictHostKeyChecking=no deployer@52.221.120.192 "cd $CI_PROJECT_NAME; docker compose pull; docker compose up -d"
